### ISSUE TITLE
Support Homebridge Version 1.0.0

### ISSUE THREAD

**Issue by egnerfl** [SeydX/homebridge-washingmachine-pow#3]
The current plugin version crashes when using Homebridge version `1.0.0`

```
[4/27/2020, 1:47:02 PM] ====================
[4/27/2020, 1:47:02 PM] ERROR LOADING PLUGIN homebridge-washingmachine-pow:
[4/27/2020, 1:47:02 PM] Error: Plugin /homebridge/node_modules/homebridge-washingmachine-pow requires a HomeBridge version of ^0.4.49 which does not satisfy the current HomeBridge version of 1.0.0. You may need to upgrade your installation of HomeBridge.
    at Plugin.load (/usr/local/lib/node_modules/homebridge/src/plugin.ts:144:13)
    at /usr/local/lib/node_modules/homebridge/src/pluginManager.ts:119:16
    at Map.forEach (<anonymous>)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:117:18)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:148:24)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:74:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
[4/27/2020, 1:47:02 PM] ====================
```

**Comment by aberfisch** [comment]
support for current and future of homebridge. Would be great. 
How can we support with this?!

`[7/9/2020, 17:56:25] The dynamic platform WMPow from the plugin homebridge-washingmachine-pow seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!`

**Comment by aberfisch** [comment]
> support for current and future of homebridge. Would be great.
> How can we support with this?!
> 
> `[7/9/2020, 17:56:25] The dynamic platform WMPow from the plugin homebridge-washingmachine-pow seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!`

OK, seems to be my own mistake with having the platform twice configured for two Power-Plugs. But can't get it fixed with my config. Should it be possible to running two power-plugs with only one WMPow platform entry?

**Comment by andreaseu** [comment]
Search also for a solution or an example Config to control 3x Pow R2 (washing machine, dryer and dishwasher) with telegram notification. 

**Error 1**

```
homebridge    | (node:397) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 15c8087e-853e-4ee5-987b-b2e850086b0a
homebridge    |     at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:414:15)
homebridge    |     at Bridge.Accessory._this.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:448:12)
homebridge    |     at Server.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:528:17)
homebridge    |     at HomebridgeAPI.emit (events.js:315:20)
homebridge    |     at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:316:10)
homebridge    |     at WMPow._addOrConfigure (/homebridge/node_modules/homebridge-washingmachine-pow/src/platform.js:155:16)
homebridge    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
homebridge    | (node:397) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Error 2**
`homebridge    | [7/15/2020, 8:42:39 PM] The plugin "homebridge-washingmachine-pow" requires a Homebridge version of ^0.4.49 which does not satisfy the current Homebridge version of 1.1.1. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.`

**MY Config**
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "aa:cc:bb:dd:ff:ee",
        "port": 51826,
        "pin": "xxx-xx-xxx"
    },
    "platforms": [
        {
            "platform": "WMPow",
            "clearCache": false,
            "devices": [
                {
                    "active": true,
                    "name": "Waschmaschine",
                    "address": "172.21.0.5",
                    "port": 1883,
                    "username": "device",
                    "password": "example",
                    "publishTopic": "cmnd/xxPowWM/TelePeriod",
                    "puplishParam": "15",
                    "subscribeTopics": {
                        "getPower": "stat/xxPowWM/POWER",
                        "getEnergy": "tele/xxPowWM/SENSOR",
                        "getState": "tele/xxPowWM/STATE",
                        "getLink": "tele/xxPowWM/LWT"
                    },
                    "sendTopics": {
                        "setPower": "cmnd/xxPowWM/power"
                    },
                    "parameter": {
                        "off": 0,
                        "standby": 2,
                        "pause": 3,
                        "active": 5
                    }
                }
            ],
            "notifier": {
                "active": true,
                "token": "xxx",
                "chatID": "xxx",
                "motionOn": "*Waschmaschine:* gestartet!",
                "motionOff": "*Waschmaschine:* fertig!"
            }
        },
        {
            "platform": "WMPow",
            "clearCache": false,
            "devices": [
                {
                    "active": true,
                    "name": "Trockner",
                    "address": "172.21.0.5",
                    "port": 1883,
                    "username": "device",
                    "password": "example",
                    "publishTopic": "cmnd/xxPowDRY/TelePeriod",
                    "puplishParam": "15",
                    "subscribeTopics": {
                        "getPower": "stat/xxPowDRY/POWER",
                        "getEnergy": "tele/xxPowDRY/SENSOR",
                        "getState": "tele/xxPowDRY/STATE",
                        "getLink": "tele/xxPowDRY/LWT"
                    },
                    "sendTopics": {
                        "setPower": "cmnd/xxPowDRY/power"
                    },
                    "parameter": {
                        "off": 0,
                        "standby": 2,
                        "pause": 3,
                        "active": 5
                    }
                }
            ],
            "notifier": {
                "active": true,
                "token": "xxx",
                "chatID": "xxx",
                "motionOn": "*Trockner:* gestartet!",
                "motionOff": "*Trockner:* fertig!"
            }
        },
        {
            "platform": "WMPow",
            "clearCache": false,
            "devices": [
                {
                    "active": true,
                    "name": "Spülmaschine",
                    "address": "172.21.0.5",
                    "port": 1883,
                    "username": "device",
                    "password": "example",
                    "publishTopic": "cmnd/xxPowSM/TelePeriod",
                    "puplishParam": "15",
                    "subscribeTopics": {
                        "getPower": "stat/xxPowSM/POWER",
                        "getEnergy": "tele/xxPowSM/SENSOR",
                        "getState": "tele/xxPowSM/STATE",
                        "getLink": "tele/xxPowSM/LWT"
                    },
                    "sendTopics": {
                        "setPower": "cmnd/xxPowSM/power"
                    },
                    "parameter": {
                        "off": 0,
                        "standby": 2,
                        "pause": 3,
                        "active": 5
                    }
                }
            ],
            "notifier": {
                "active": true,
                "token": "xxx",
                "chatID": "xxx",
                "motionOn": "*Spülmaschine:* gestartet!",
                "motionOff": "*Spülmaschine:* fertig!"
            }
        }
    ],
    "accessories": [
        {

        }
    ]
}
```

**Comment by aberfisch** [comment]
> > support for current and future of homebridge. Would be great.
> > How can we support with this?!
> > `[7/9/2020, 17:56:25] The dynamic platform WMPow from the plugin homebridge-washingmachine-pow seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!`
> 
> OK, seems to be my own mistake with having the platform twice configured for two Power-Plugs. But can't get it fixed with my config. Should it be possible to running two power-plugs with only one WMPow platform entry?

No, need for this plug-in anymore. I switched to mqttthing --> https://github.com/arachnetech/homebridge-mqttthing/wiki/Tested-Configurations#Outlets-and-Plugs

**Comment by andreaseu** [comment]
Maybe you have an example of your configuration? Can the plugin also send a notification. @aberfisch

**Comment by seydx** [comment]
Fixed in v2
