### ISSUE TITLE
Multiple chatID/Messages

### ISSUE THREAD

**Issue by jannnfe** [SeydX/homebridge-washingmachine-pow#6]
Hello,

my config looks like this:
```
{
            "name": "TasmotaPOW",
            "debug": true,
            "devices": [
                {
                    "name": "Keller Waschmaschine",
                    "ip": "192.168.2.11",
                    "port": 1883,
                    "username": "XXX",
                    "password": "XXXXXX",
                    "manufacturer": "Gosund",
                    "model": "SP111 v1.1 Module",
                    "serialNumber": "192.168.2.20",
                    "onValue": "ON",
                    "offValue": "OFF",
                    "startValue": 5,
                    "motionSensor": false,
                    "topics": {
                        "stateGet": "stat/Waschmaschine/POWER",
                        "statusGet": "tele/Waschmaschine/STATE",
                        "energyGet": "tele/Waschmaschine/SENSOR",
                        "statusSet": "cmnd/Waschmaschine/POWER",
                        "resetSet": [
                            "cmnd/Waschmaschine/EnergyReset1"
                        ]
                    }
                }
            ],
            "telegram": {
                "active": true,
                "token": "XXXX:YYYY",
                "chatID": "XXXX"
            },
            "platform": "WMPow"
        }
```

Every time I like to switch the outlet in Home i got this error in the log of homebridge:
```
SyntaxError: Unexpected token O in JSON at position 0
    at JSON.parse (<anonymous>)
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-washingmachine-pow/src/accessories/outlet.js:151:26)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._handlePublish (/usr/local/lib/node_modules/homebridge-washingmachine-pow/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-washingmachine-pow/node_modules/mqtt/lib/client.js:410:12)
    at work (/usr/local/lib/node_modules/homebridge-washingmachine-pow/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-washingmachine-pow/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/usr/local/lib/node_modules/homebridge-washingmachine-pow/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/usr/local/lib/node_modules/homebridge-washingmachine-pow/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/usr/local/lib/node_modules/homebridge-washingmachine-pow/node_modules/readable-stream/lib/_stream_writable.js:307:11)
```

Version: v2.0.7
Homebridge: v1.1.7
Node: v14.15.3
NPM: v6.14.10

----

Second Question: How to add multiple ChatIDs and how to add different Message for different Device?
Example: Waschmaschine: "Waschmaschine fertig" - Trockner: "Trockner fertig"

Thanks! :)

**Comment by jannnfe** [comment]
Okay first Question is fixed. I used the wrong "stateGet". In your example Config it is:
"stateGet": "tele/Waschmaschine/STATE",
I have to use:
"stateGet": "stat/Waschmaschine/RESULT"

But what's about second question?

**Comment by seydx** [comment]
added in v2.1.0
